### ISSUE TITLE
Wrong source download url while building jdk

### ISSUE THREAD

**Issue by alikve** [idlemoor/slackrepo#7]
I use version 0.2.0rc1. After the command
`# slackrepo build jdk`
I got the following message:

```
Testing SlackBuild files ... done.
:-/ development/jdk SKIPPED Source not available /-:
Please download the source
  from: https://download.oracle.com/otn-pub/java/jdk/8u45-b14/jdk.tar.gz
  to:   /var/lib/slackrepo/SBo/source/development/jdk/x86_64
```

This url is wrong, in particular, the source file should have the name
`jdk-8u45-linux-x64.tar.gz`.

After downloading the correct file slackrepo build the package without problems.

**Comment by slackpanos** [comment]
You must manual download the source because jdk have a license and Oracle wants to accept it first...

**Comment by alikve** [comment]
Yes, of course, but the issue is that the slackrepo provides a wrong url for this.

**Comment by slackpanos** [comment]
Slackrepo reads the .info files from SBo (http://slackbuilds.org/slackbuilds/14.1/development/jdk/jdk.info) 
and this is SBo problem... SBo cannot host the source to alternative
location due to licence. From readme of jdk.SlackBuild:
You must Agree to Oracle's download agreement before this can be downloaded.
This means you have to use a web browser to download it. Sorry wget folks.

**Comment by alikve** [comment]
I see, so, this is a bug in jdk.info.  Still strange why slackrepo changed `jdk-8u45-linux-x64.tar.gz` in the .info-url to `jdk.tar.gz`
